### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by jordan-powers** [momentumfrc/Scouting-Website#13]
We need a list of different categories to enter into the database about each robot.

**Comment by fabiocolacio** [comment]
yeah I will start brainstorming on those tomorrow.

Another semi-related thought I have is to list the team numbers in home.php instead of everything for each team. Eventually there will be a lot of information and possibly even pictures for each robot, so most of it should be hidden away until someone clicks on the team they are looking for, otherwise it will get wonky, especially on mobile, where most people will be using this.

**Comment by fabiocolacio** [comment]
I added databaseideas.md to explain ideas for what the categories should be. The page to add/edit robots should reflect the type of field that is there (checkboxes for y/n, number entry for weight, etc.).

We should show that file to mentors and team members to see if they have further improvements or changes to make.

**Comment by jordan-powers** [comment]
I agree the homepage should only list team numbers. For the different entry options, a switch statement in the php could place a different form element for each field. I'll close the issue and work on implementing the various changes.
